version: '3'

services:
  redis:
    image: redis:5.0.7
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  flask:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=your_mum
      - SESSION_REDIS=redis://redis:6379
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis
    stdin_open: true
    tty: true

volumes:
  redis_data:
