---
- name: create directory for socket
  become: yes
  become_method: sudo
  file:
    group: "{{ project_user }}"
    owner: "{{ project_user }}"
    path: "{{ socket_directory }}"
    state: directory
    mode: "0770"

- name: template a file to /etc/uwsgi/apps-available/my_site.ini
  become: yes
  become_method: sudo
  template:
    src: roles/uwsgi/templates/my_site.j2
    dest: /etc/uwsgi/apps-available/my_site.ini
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0500"

- name: create symbolic link to /etc/uwsgi/sites-enabled
  become: yes
  become_method: sudo
  file:
    src: /etc/uwsgi/sites-available/my_site.ini
    dest: /etc/uwsgi/sites-enabled/my_site.ini
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    state: link
