---
- name: install system packages
  become: yes
  become_method: sudo
  apt:
    update_cache: true
    pkg:
      - acl
      - python-dev
      - python3-pip
      - libfontconfig
      - nginx
      - redis-server
      - uwsgi
      - uwsgi-plugin-python3
      - wkhtmltopdf
      - xvfb
